language: node_js

node_js:
- '7'

before_script:
- npm install

script: npm run dist

cache:
  directories:
  - node_modules

deploy:
  provider: npm
  email: fr33wayz@gmail.com
  api_key:
    secure: tdZ1Fq9zUP3r23d4uiLazpVtjyKXUnP4GoTG9EThVWhJ2VKaSqNbMjF4K5fxxuv7+PwxtpNajkfL/xZSbnXlGrfKu4s86bmtMdL/y/QjnNaW/LHVdWc+9PrJv9HmFAkLd2gAADrtilx7+lIWcQ3K06ruQqdBWaYPoyUYsy7/b8bkOf8ktv/BhhANhF6NOZMb2TYhuD9hPEmmnxbFWzEcMc3mKrgrZ7usvyBi3LNJOb9Wt4RbGcXbdoqZu2pjWzM5ZVjf8eO9Uz5yVHsg2/EwLAbuVNb/FiaN5EksDVm99/lKKC/eh+lGC7p9IxHx7uxMV5r7o+a3Gdgq9XbYLeQJcF37e9Fbb0w+xiKH5e3o12zwVa8RFrtMWcm4O5mTbKOE3ttXZEwuXqYsH+HRs77A2uCLQq8UPlS4Pim9kD73kZ89UdNWpJ+YkJHO/WdGdblo4fBkIzTbjW50R6x0xDCOBXDwJ/dIr3fHadeNyJzp34yNJP2n/yWbQmBcesvdIpdjkJ9ScPpJTUQVn6SssvMFwV35nbXttjA4fCKc370bGsyVqdgo8UtuGxOeSght93AwdCJsodBPWrLXpBKcc87Tp2EljXOd40iz4oaBxZK67Gg4CFGOsN6BeELKNH5ZGsHJtWiklsxk7rBGR7Udde/wbPMyRiKRGtZ4ut51tFxgxXQ=
  on:
    branch: master